<a href="https://colab.research.google.com/github/Sameen-55/python6/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(a+b)


[ 2  4  6  8 10 12]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(a-b)

[0 0 0 0 0 0]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(a*b)

[ 1  4  9 16 25 36]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(a/b)

[1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(a//b)

[1 1 1 1 1 1]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(2*a-b)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,4,5,6])
print(a*2-3*b)

[-1 -2 -3 -4 -5 -6]


In [ ]:
import numpy as np
a = np.zeros([1,2,3,4,5,6])

print(a)

[[[[[[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]]

    [[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]]

    [[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]]

    [[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]]]


   [[[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]]

    [[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]]

    [[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]]

    [[0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 0. 0. 0. 0. 0.]
     [0. 

In [ ]:
import numpy as np
a = np.ones([1,2,3,4,5,6])
print(a)

[[[[[[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]]

    [[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]]

    [[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]]

    [[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]]]


   [[[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]]

    [[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]]

    [[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]]

    [[1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 1. 1. 1. 1. 1.]
     [1. 

In [ ]:
ones_arr = np.ones((3, 2))  # 3 rows, 2 columns
print("Ones Array:\n", ones_arr)
print("Shape:", ones_arr.shape, "Dimension:", ones_arr.ndim)
print("-" * 30)


Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Shape: (3, 2) Dimension: 2
------------------------------


In [ ]:
a=np.empty([1,2,3])
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
a = np.full((2,3),5)
print(a)
# 2 represent 2 row
# 3 represent 5 coulums
#5 fill in row and coulums


[[5 5 5]
 [5 5 5]]


In [ ]:
a =np.arange(0,10,2)
print(a)
# 0 represent start 0
# 10 represent range
# 2 difference create 2 numbers

[0 2 4 6 8]


In [ ]:
a = np.linspace(0,1,2)
print(a)
#start 0
# 1 represent means number
# 2 range number of 2 times print

[0. 1.]


In [ ]:
a = np.array(5)
print(a.ndim)
print(a.shape)  # 0

0
()


In [ ]:
b = np.array([1,2,3])
print(b.ndim)  # 1
print(b.shape) # (3,)

1
(3,)
